---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup}
library(CovMitigation)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
```

```{r runsims}
baseparms <- list(I0=0, E0=1)
r3 <- run_scenario(180, c(baseparms, list(A0=3, T0=5)), 'A0=3')
r2 <- run_scenario(180, c(baseparms, list(A0=1, T0=5)), 'A0=1')
r1 <- run_scenario(180, c(baseparms, list(A0=0.01, T0=5)), 'A0=0')
r4 <- run_scenario(180, c(baseparms, list(A0=3, T0=5, Ts=1)), 'A0=3, Ts=1')

pltdata <- bind_rows(r1,r2,r3,r4) %>%
  group_by(time, scenario) %>%
  summarise(
            newCases = sum(newCases*marketFraction),
            PopSympto = sum(PopSympto*marketFraction),
            PopInfection = sum(PopInfection*marketFraction),
            PopCumulInfection = sum(PopCumulInfection*marketFraction),
            PopCumulFrac = sum(PopCumulInfection)/sum(population*marketFraction),
            popTotal = sum(population*marketFraction)
            )
```

```{r plotsims}
## Plot cumulative infected
plt_cum <- ggplot(data=pltdata, aes(x=time, y=PopCumulInfection, color=scenario)) + geom_line(size=1.2) + scale_y_log10(minor_breaks=c(20,40,80,160,320,640,1280,2560)) + theme_bw() + scale_color_solarized() + scale_x_continuous(minor_breaks = seq(5,50), limits=c(5,50))
print(plt_cum)

## Plot new cases
plt_new <- ggplot(data=pltdata, aes(x=time, y=newCases, color=scenario)) + geom_line(size=1.2) +
  theme_bw() + scale_color_solarized()
print(plt_new)

## Plot symptomatic fraction
pltdata <- mutate(pltdata, fs = PopSympto / PopInfection)
plt_sympfrac <- ggplot(data=pltdata, aes(x=time, y=fs, color=scenario)) + geom_line(size=1.2) +
  theme_bw() + scale_color_solarized()
print(plt_sympfrac)

## plot asymptomatic vs symptomatic cases
pd <- select(pltdata, time, scenario, PopInfection, PopSympto) %>% 
  pivot_longer(PopInfection:PopSympto, names_to='symptoms', values_to='count')
plt_symp <- ggplot(data=pd, aes(x=time, y=count, color=scenario)) + geom_line(size=1.2) +
  facet_wrap(~symptoms) +
  theme_bw() + scale_color_solarized()
print(plt_symp)


## plot cumulative impacted population fraction
plt_ifrac <- ggplot(data=pltdata, aes(x=time, y=PopCumulFrac, color=scenario)) + geom_line(size=1.2) +
  theme_bw() + scale_color_solarized()
print(plt_ifrac)
```

