---
title: "COVID-19 Growth in Virginia"
author: "Robert Link"
date: "4/1/2020"
output: html_document
---

```{r setup}
library(dplyr)
library(tidyr)
library(ggplot2)
library(CovMitigation)
library(ggthemes)
library(latex2exp)
```

```{r growthrate}
pltdata <- 
  select(uvads_covid19, date, vaNewCases) %>%
  filter(vaNewCases > 0)
t <- seq_along(pltdata$date) - 1  # start at zero
pltdata$t <- t

## Label positioning
lastidx <- length(t)
lastdate <- pltdata$date[lastidx]

## Create the benchmark data
tds <- c(3,4,5,6,7)
tdlabs <- paste('td=',tds)
tdlabstex <- sprintf('$t_d = %d$', tds)
gr <- lapply(tds, 
             function(td) {
               r <- log(2)/td
               exp(r*t)
             })
benchmarks <- as.data.frame(gr)
names(benchmarks) <- tdlabs
benchmarks$date <- t + pltdata$date[1]
benchmarks <- pivot_longer(benchmarks, -date, names_to = 'doubling time')
benchplt <- 
  ggplot(data=pltdata, aes(x=date, y=vaNewCases)) + 
  geom_line(data=pltdata, mapping=aes(y=vaNewCases), size=1.2) +
  geom_line(data=benchmarks, mapping=aes(y=value, group=`doubling time`), color='lightgrey') +
  scale_color_solarized() +
  scale_y_log10() +
  #geom_label(x=lastdate, y=log10(gr[[1]][lastidx]), label=tdlabs[1]) +
  theme_bw()
for(i in seq_along(gr)) {
  benchplt <- benchplt + geom_label(x=lastdate, y=log10(gr[[i]][lastidx]), label=TeX(tdlabstex[i]))
}
suppressWarnings(print(benchplt))
```
