---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(doParallel)
library(dplyr)
library(here)
library(metrosamp)
library(ggplot2)
library(ggthemes)
library(tidyr)
library(CovMitigation)

registerDoParallel(8)

mkdensplt <- function(samps) {
  varnames <- colnames(samps)
  pltdata <- pivot_longer(as.data.frame(samps), everything(), names_to = 'parameter')
  pltdata$parameter <- factor(pltdata$parameter, levels=varnames, ordered=TRUE)
  ggplot(data=pltdata, aes(x=value)) + geom_density(fill='LightGrey', alpha=0.5) + facet_wrap(~parameter, scales='free') +
    theme_bw()
}

set.seed(867-5309)
```

```{r loaddata}
datadir <- here('analysis', 'mcmc-rslts', 'mcmc-test-v3')
warmup_files <- list.files(path=datadir, pattern='mcmc-ckpt.*\\.rds', full.names=TRUE)

warmups <- lapply(warmup_files, readRDS)
warmups <- recover_ckpt(warmups)

cwarmups <- metrosamp2coda(warmups, 2500)
```

## Expectation value and credible intervals
```{r basicanalysis}
cat('\nAcceptance ratio by chain:\n')
sapply(warmups, accrate)
cat('\nOverall acceptance rate:\n')
accrate(warmups)
cat('\nEffective samples:\n')
print(neff(warmups))
cat('Expectation values:\n')
print(signif(EV(warmups), 2))
cat('\nCredible intervals:\n')
print(signif(CI(warmups), 2))
cat('\nRhat statistic:\n')
coda::gelman.diag(cwarmups)
```

## Density plots

```{r densplots}
allsamps <- getsamples(warmups, thinto=1600)
mkdensplt(allsamps)
```

```{r sampleruns}
Nsamp <- 250
parmsamps <- rsample(warmups, Nsamp)
runparms <- function(parms, scenname) {
  modparms <- parms[c('eta','xi','zeta', 'A0', 'D0', 'Ts', 'I0', 'mask_effect')]
  day_zero <- 30
  raw <- run_scenario(270, as.list(modparms), scenarioName = scenname)
  totalUVA <- 
    group_by(raw, time, scenario) %>% 
    summarise(
      popmkt = sum(population*marketFraction),
      newCases = sum(newCases*marketFraction),
      newSympto = sum(newSympto * marketFraction),
      PopSympto = sum(PopSympto*marketFraction),
      PopInfection = sum(PopInfection*marketFraction),
      fracInfection = PopInfection / popmkt,
      PopCumulInfection = sum(PopCumulInfection*marketFraction),
      fracCumulInfection = PopCumulInfection/popmkt
    ) %>%
    ungroup()
  dt <- totalUVA$time + day_zero
  dateout <- dt + as.Date('2020-01-01')
  mutate(totalUVA, time=dt, date=dateout)
}

sample_runs <- 
  lapply(seq(1,Nsamp), 
         function(i) {
           parms <- parmsamps[i,]
           runparms(parms, as.character(i))
         }) %>%
  bind_rows()

ev_run <- runparms(EV(warmups), 'EV')
map_run <- runparms(MAP(warmups), 'MAP')
```


```{r modobs}
mapev <- rbind(EV(warmups), MAP(warmups))
viscounties <- c('AlbemarleCounty', 'Charlottesvillecity', 'NelsonCounty',  ## Thomas Jefferson district
                 'FairfaxCounty', 'ArlingtonCounty', 'PrinceWilliamCounty',  ## Northern Virginia
                 'Richmondcity', 'HenricoCounty', 'ChesterfieldCounty'      ## Richmond area
)
plt_modobs(mapev, c('EV', 'MAP'), counties = viscounties, default_parms=list(day_zero=30)) + scale_color_solarized()
plt_projections(mapev, c('EV', 'MAP'), what='PopInfection') + scale_color_solarized()
```

```{r ribbonplot}
strtdate <- as.Date('2020-07-01')
enddate <- as.Date('2020-10-01')
ci_by_date <- 
  filter(sample_runs, date >= strtdate, date < enddate) %>%
  #mutate(time = as.numeric(date-strtdate)) %>%
  group_by(date) %>%
  summarise(nslo = quantile(newSympto, 0.1), nshi = quantile(newSympto, 0.9)) %>%
  ungroup()

pltev <- filter(ev_run, date >= strtdate, date < enddate)

rplt <- 
  ggplot(data=pltev, aes(x=date)) + 
  geom_line(aes(y=newSympto), size=1.2) +
  geom_ribbon(data=ci_by_date, aes(ymin=nslo, ymax=nshi), alpha=0.5) +
  theme_bw()
print(rplt)
```

## Improving the sampling

The acceptance rate is really high, which is contributing to both poor sampling
efficiency and poor mixing.  Ideally we would want to make the sampling steps
large enough that the chains might be able to mix, but that may give us an 
acceptance rate that is too low, but it's worth a try.

```{r cor}
covm <- cov(allsamps)
signif(covm,3)
```

```{r genscen}
pltdata <- basescens %>%
  dplyr::group_by(time, scenario) %>%
  dplyr::summarise(
    newCases = sum(newCases*marketFraction),
    PopSympto = sum(PopSympto*marketFraction),
    PopInfection = sum(PopInfection*marketFraction),
    PopCumulInfection = sum(PopCumulInfection*marketFraction),
    PopCumulFrac = sum(PopCumulInfection)/sum(population*marketFraction),
    popTotal = sum(population*marketFraction)
  )
```
